---
- name: Playbook to install packages
  hosts: webservers
  become: true
  tasks:
  - name: Installing many packages in one task
    yum: 
    # name: [ 'git', 'make', 'gzip']
      name: "{{ item }}"
      state: present
    with_items:
      - telnet
      - gcc
      - tree      
