---
- name: Playbook to install and start  httpd and apache2 service packages
  hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
    ignore_errors: yes
   
  - name: Start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes
        	  
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    ignore_errors: yes

  - name: sajina-start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

