---
- name: Playbook to uninstall apache2 on ubuntu server
  hosts: dbservers
  become: true
  tasks:
  - name: stop apche2 service
    service:
      name: apache2
      state: stopped
  - name: install apache2
    apt:
      name: apache2
      state: absent
