---
- name: Playbook to stop httpd service and uninstall 
  hosts: all
  become: true
  tasks:
  - name: Stop httpd service on Redhat servers
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: uninstall httpd on Redhat servers
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: stop apache2 service on Ubuntu server
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall apache2 on Ubuntu server
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
